"""Add wallet table

Revision ID: 75f1ced51de6
Revises:
Create Date: 2025-07-22 19:35:46.659001

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75f1ced51de6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="Wallet ID"
        ),
        sa.Column(
            "network",
            sa.Enum("TRON", name="networkenum"),
            nullable=False,
            comment="Network",
        ),
        sa.Column(
            "address", sa.String(length=255), nullable=False, comment="Wallet address"
        ),
        sa.Column(
            "balance",
            sa.DECIMAL(precision=18, scale=6),
            nullable=True,
            comment="Wallet balance",
        ),
        sa.Column("bandwidth", sa.Integer(), nullable=True, comment="Wallet bandwidth"),
        sa.Column("energy", sa.Integer(), nullable=True, comment="Wallet energy"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Created at",
        ),
        sa.CheckConstraint("balance >= 0", name="check_balance_positive"),
        sa.CheckConstraint("bandwidth >= 0", name="check_bandwidth_positive"),
        sa.CheckConstraint("energy >= 0", name="check_energy_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=False)
    op.create_index(op.f("ix_wallets_network"), "wallets", ["network"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_network"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
