default_install_hook_types: [pre-commit, post-checkout, post-merge, commit-msg]
exclude: "^(db/alembic|dev.sh)"
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            --scopes,
            "api,constants,db,enums,exceptions,explorers,repositories,schemas,settings,usecases",
            --strict,
            feat,
            fix,
            docs,
            style,
            refactor,
            test,
            chore,
            build,
            wip,
            ci,
          ]
  - repo: https://github.com/python-poetry/poetry
    rev: 2.0.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
        args: ["--with", "dev,tests"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--in-place"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--config=./pyproject.toml"]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        args: ["--settings-path=./pyproject.toml"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: ["--config", "./pyproject.toml"]
